In [1]:
import pandas as pd
import openpyxl

In [2]:
read_exc = pd.read_excel(r'C:\Users\light\Dropbox\Lightspeed Delivery, LLC\Python\Python Course\df_pymethods.xlsx')

In [3]:
df_python = pd.DataFrame(read_exc)

In [5]:
df_python[30:]

,name,desc,Examples,Import Command
30,elif,(else if) keyword used in a conditional statem...,NaN,NaN
31,enumerate,function to iterate over a sequence and get in...,NaN,NaN
32,extend,method of a list to add multiple items to the ...,NaN,NaN
33,fillna,a pandas method that fills missing values with...,NaN,NaN
34,float,built-in data type to represent a floating-poi...,NaN,NaN
35,fmean,a numpy function that computes the arithmetic ...,NaN,NaN
36,for_loop,type of loop that iterates over a collection a...,NaN,NaN
37,format,"function to format strings, used to replace pl...",NaN,NaN
38,fromkeys,a built-in dictionary method that creates a ne...,NaN,NaN
39,globals,built-in dictionary containing global variables.,NaN,NaN
40,hash,a function that converts an input value into a...,NaN,NaN
41,id,function to get the identity of an object in m...,NaN,NaN
42,if_else,"(Not a built-in function, but rather a concept...",NaN,NaN
43,init,"magic method for initializing an object, calle...",NaN,NaN
44,input(),new method description,NaN,NaN
45,insert,method of a list to insert an item at a specif...,NaN,NaN
46,isinstance(),Return whether an object is an instance of a c...,NaN,NaN
47,issubclass(),Return whether 'cls' is a derived from another...,NaN,NaN
48,iter(),Get an iterator from an object. In the first ...,NaN,NaN
49,keys,a dictionary view that displays a list of all ...,NaN,NaN
50,len,built-in function to get the length of an obje...,NaN,NaN
51,list,built-in data type to store ordered collection...,NaN,NaN
52,lower,method of string to convert all characters to ...,NaN,NaN
53,mean,the average of a set of numbers,NaN,NaN
54,name,desc,NaN,NaN
55,items(),"Iterates over the DataFrame columns, returning...",NaN,NaN
56,.values,Return Series as ndarray or ndarray-like depen...,NaN,NaN
57,.shape,number of rows and columns in dataframe,NaN,NaN
58,next(),Return the next item from the iterator. If def...,NaN,NaN
59,ord,function to get the unicode code point of a si...,NaN,NaN
60,pandas,an open-source library for data analysis and m...,NaN,NaN
61,perf_counter(),A function that returns the value (in seconds)...,NaN,NaN
62,raise ValueError(),exception object ('custom message'),NaN,NaN
63,range,"function to generate a sequence of numbers, ty...",NaN,NaN
64,repr(),Return the canonical string representation of ...,NaN,NaN
65,rstrip,method of string to remove whitespaces from th...,NaN,NaN
66,set,a built-in Python data type that stores an uno...,NaN,NaN
67,slice,"object to extract a portion of a sequence, suc...",NaN,NaN
68,sqrt(),A function that returns the square root of a n...,NaN,NaN
69,String Library,A collection of string-related functions in Py...,NaN,NaN
70,str,built-in function to convert any object to a s...,NaN,NaN
71,sum,built-in function to add items of an iterable ...,NaN,NaN
72,ternary conditional operator,shorthand syntax to write an if-else statement...,NaN,NaN
73,timer,(Not a built-in function) refers to a way to m...,NaN,NaN
74,title,method of string to convert the first letter o...,NaN,NaN
75,tuple,built-in data type to store ordered collection...,NaN,NaN
76,upper,method of string to convert all characters to ...,NaN,NaN
77,|,"Bitwise OR operation between two sets, returns...",NaN,NaN
78,datetime,"datetime(year, month, day[, hour[, minute[, se...",NaN,from datetime import datetime
79,matrix function,generates a matrix using a function and parama...,"gen_matrix(rows=4, cols=8, default_value=1)",NaN
80,print(*'abc'),star argument to separate print of 'abc',print(*'abc') generates: a b c ///// print(*'a...,NaN
81,iterables,"Lists, tuples, dictionaries, and sets are all ...",NaN,NaN
82,iterators,NaN,NaN,NaN
83,lambda,anonymous function,"lambda a, b: a + b",NaN
84,__next__(),used to access next element after the iter() f...,NaN,NaN