In [4]:
# method_name = ['format', 'abs', 'float', 'range', '__add__', 'as_integer_ratio',
# 'id' ]
method_name = [
    {0: 'format', 'description': 'The format() method formats the specified value(s) and insert them inside the string placeholder.'},
    {0: 'abs', 'description': 'The format() method formats the specified value(s) and insert them inside the string placeholder.'},
    {0: 'float', 'description': 'The format() method formats the specified value(s) and insert them inside the string placeholder.'},
    {0: 'range', 'description': 'The format() method formats the specified value(s) and insert them inside the string placeholder.'},
    {0: '__add__', 'description': 'The format() method formats the specified value(s) and insert them inside the string placeholder.'},
    {0: 'as_integer_ratio', 'description': 'The format() method formats the specified value(s) and insert them inside the string placeholder.'},
    {0: 'id', 'description': 'The format() method formats the specified value(s) and insert them inside the string placeholder.'},
    {0: '__init__', 'description': 'The __init__ function is called every time an object is created from a class. The __init__ method lets the class initialize the object attributes and serves no other purpose. It is only used within classes.'},
    {0: 'ord', 'description': ''},
    {0: 'str(string)', 'description': ''},
    {0: 'len', 'description': ''},
    {0: '', 'description': ''},
    {0: 'if_else', 'description': ''},
    {0: 'elif', 'description': ''},
    {0: 'ternary conditional operator', 'description': ''},
    {0: 'list', 'description': ''},
    {0: 'tuple', 'description': ''},
    {0: 'slice', 'description': ''},
    {0: 'del', 'description': ''},
    {0: 'append', 'description': ''},
    {0: 'extend', 'description': ''},
    {0: 'insert', 'description': ''},
    {0: 'timer', 'description': 'from timeit import timeit'},
    {0: 'globals', 'description': ''},
    {0: 'copy', 'description': ''},
    {0: 'deepcopy', 'description': 'from copy import deepcopy'},
    {0: 'upper', 'description': ''},
    {0: 'lower', 'description': ''},
    {0: 'title', 'description': ''},
    {0: 'casefold', 'description': 'Case folding is actually defined by the Unicode standard, and is used to perform case insensitive comparisons. Although it may look like case folding is just using lower case, it is **not** always the case.'},
    {0: 'rstrip', 'description': ''},
    {0: 'for_loop', 'description': ''},
    {0: 'enumerate', 'description': ''},
    {0: 'sum', 'description': ''},
    {0: 'mean', 'description': ''},
    {0: 'fmean', 'description': ''},
    {0: 'fillna', 'description': ''},
    {0: 'pandas', 'description': 'import pandas as pd'},
    {0: 'dict(dictionaries)', 'description': ''},
    {0: 'hash', 'description': ''},
    {0: '.DataFrame()', 'description': ''},
    {0: '.clear()', 'description': ''},
    {0: 'keys', 'description': ''},
    {0: 'fromkeys', 'description': ''},
    {0: '.get()', 'description': ''},
    {0: '.update()', 'description': ''},
    {0: 'set()', 'description': ''},
    {0: '.isdisjoint()', 'description': ''},
    {0: '.add()', 'description': ''},
    {0: '.remove()', 'description': ''},
    {0: '.discard()', 'description': ''},
    {0: '&', 'description': ''},
    {0: '|', 'description': ''},
    {0: '**', 'description': ''},
    {0: '*', 'description': ''},
    {0: '=', 'description': ''},
    {0: '==', 'description': ''},
    {0: 'String Library', 'description': 'import string'},
    {0: '.ascii_upper', 'description': ''},
    {0: '.ascii_lower', 'description': ''},
    {0: '.ascii_letters', 'description': ''},
    {0: 'sqrt()', 'description': ''},
    {0: 'perf_counter()', 'description': 'from time import perf_counter'},
    {0: '.split()', 'description': ''},
    {0: '.items()', 'description': ''},
    {0: '.value', 'description': ''},
    {0: '.replace()', 'description': ''},
    {0: 'Counter()', 'description': 'from collections import Counter'},
]

In [5]:
import pandas as pd

In [6]:
df_pymethods = pd.DataFrame(method_name)

In [7]:
df_pymethods[50:][0]

50        .discard()
51                 &
52                 |
53                **
54                 *
55                 =
56                ==
57    String Library
58      .ascii_upper
59      .ascii_lower
60    .ascii_letters
61            sqrt()
62    perf_counter()
63          .split()
64          .items()
65            .value
66        .replace()
67         Counter()
Name: 0, dtype: object

In [8]:
df_pymethods

             0                                        description
0       format  The format() method formats the specified valu...
1          abs  The format() method formats the specified valu...
2        float  The format() method formats the specified valu...
3        range  The format() method formats the specified valu...
4      __add__  The format() method formats the specified valu...
..         ...                                                ...
63    .split()
64    .items()
65      .value
66  .replace()
67   Counter()                    from collections import Counter

[68 rows x 2 columns]

In [9]:
method_desc = {
"format": "function to format strings, used to replace placeholders in a string with actual values.",
"abs": "function to get absolute value of a number.",
"float": "built-in data type to represent a floating-point number.",
"range": "function to generate a sequence of numbers, typically used in a for loop.",
"add": "magic method to overload the '+' operator, typically used to define custom addition behavior for objects.",
"as_integer_ratio": "method of float to get a numerator and denominator for representing a float as a rational number.",
"id": "function to get the identity of an object in memory.",
"init": "magic method for initializing an object, called when object is created.",
"ord": "function to get the unicode code point of a single character.",
"str": "built-in function to convert any object to a string representation.",
"len": "built-in function to get the length of an object, such as a list or string.",
"if_else": "(Not a built-in function, but rather a concept in programming) conditional statement to execute different code blocks based on a boolean expression.",
"elif": "(else if) keyword used in a conditional statement to provide additional cases to test.",
"ternary conditional operator": "shorthand syntax to write an if-else statement in a single line.",
"list": "built-in data type to store ordered collection of objects, mutable.",
"tuple": "built-in data type to store ordered collection of objects, immutable.",
"slice": "object to extract a portion of a sequence, such as a list or string.",
"del": "statement to delete an object, such as an item in a list.",
"append": "method of a list to add an item to the end of the list.",
"extend": "method of a list to add multiple items to the end of the list.",
"insert": "method of a list to insert an item at a specific position.",
"timer": "(Not a built-in function) refers to a way to measure the time taken by a section of code to execute.",
"globals": "built-in dictionary containing global variables.",
"copy": "module to create shallow or deep copies of objects.",
"deepcopy": "function in the copy module to create a deep copy of an object.",
"upper": "method of string to convert all characters to uppercase.",
"lower": "method of string to convert all characters to lowercase.",
"title": "method of string to convert the first letter of each word to uppercase.",
"casefold": "method of string to convert string to a case-insensitive form.",
"rstrip": "method of string to remove whitespaces from the right end of the string.",
"for_loop": "type of loop that iterates over a collection and executes a block of code for each iteration.",
"enumerate": "function to iterate over a sequence and get index and value for each item.",
"sum": "built-in function to add items of an iterable and return the sum.",
'mean': 'the average of a set of numbers',
'fmean': 'a numpy function that computes the arithmetic mean of input elements, ignoring NaN values',
'fillna': 'a pandas method that fills missing values with a specified value or method',
'pandas': 'an open-source library for data analysis and manipulation in Python',
'dict': 'short for dictionary, a built-in Python data type that stores key-value pairs',
'hash': 'a function that converts an input value into a fixed-size output value (hash code)',
'.DataFrame()': 'a pandas constructor that creates a dataframe from various inputs',
'.clear()': 'a dictionary method that removes all items from the dictionary',
'keys': 'a dictionary view that displays a list of all keys in a dictionary',
'fromkeys': 'a built-in dictionary method that creates a new dictionary with specified keys and values',
'.get()': 'a dictionary method that retrieves the value of a specified key and returns None if the key is not found',
'.update()': 'a dictionary method that updates the dictionary with the key-value pairs from another dictionary or from an iterable object',
'set': 'a built-in Python data type that stores an unordered collection of unique elements',
'.isdisjoint()': 'a set method that returns True if two sets have no elements in common, and False otherwise',
'.add()': 'a set method that adds an element to the set',
'.remove()': 'a set method that removes a specified element from the set.',
 'discard()': 'Removes an element from a set, if it is present',
 'discard()': 'Removes an element from a set, if it is present',
'&': 'Bitwise AND operation between two sets, returns elements present in both sets',
'|': 'Bitwise OR operation between two sets, returns elements present in either set',
'**': 'Exponentiation operator, raises the first operand to the power of the second',
'*': 'Multiplication operator, returns the product of two operands',
'=': 'Assignment operator, assigns the value of the second operand to the first',
'==': 'Equality operator, returns True if both operands are equal, else False',
'String Library': 'A collection of string-related functions in Python',
'.ascii_upper': 'A string of the uppercase letters "A" through "Z", ASCII codes 65 to 90',
'.ascii_lower': 'A string of the lowercase letters "a" through "z", ASCII codes 97 to 122',
'.ascii_letters': 'A string of all the ASCII letters "a" through "z" and "A" through "Z"',
'sqrt()': 'A function that returns the square root of a number',
'perf_counter()': 'A function that returns the value (in seconds) of a performance counter, a monotonically increasing timer',
'.split()': 'A string method that returns a list of strings by splitting a string into substrings based on a specified separator',
'.items()': 'A method that returns a view of the dictionarys items as key-value pairs',
'.value': 'An attribute or method that retrieves the value associated with a key in a dictionary',
'.replace()': 'A string method that returns a copy of the string with specified replacements made',
'Counter()': 'A built-in Python collection that counts the number of occurrences of elements in a list or other iterable'}

In [10]:
method_desc

{'format': 'function to format strings, used to replace placeholders in a string with actual values.',
 'abs': 'function to get absolute value of a number.',
 'float': 'built-in data type to represent a floating-point number.',
 'range': 'function to generate a sequence of numbers, typically used in a for loop.',
 'add': "magic method to overload the '+' operator, typically used to define custom addition behavior for objects.",
 'as_integer_ratio': 'method of float to get a numerator and denominator for representing a float as a rational number.',
 'id': 'function to get the identity of an object in memory.',
 'init': 'magic method for initializing an object, called when object is created.',
 'ord': 'function to get the unicode code point of a single character.',
 'str': 'built-in function to convert any object to a string representation.',
 'len': 'built-in function to get the length of an object, such as a list or string.',
 'if_else': '(Not a built-in function, but rather a concept in programming) conditional statement to execute different code blocks based on a boolean expression.',
 'elif': '(else if) keyword used in a conditional statement to provide additional cases to test.',
 'ternary conditional operator': 'shorthand syntax to write an if-else statement in a single line.',
 'list': 'built-in data type to store ordered collection of objects, mutable.',
 'tuple': 'built-in data type to store ordered collection of objects, immutable.',
 'slice': 'object to extract a portion of a sequence, such as a list or string.',
 'del': 'statement to delete an object, such as an item in a list.',
 'append': 'method of a list to add an item to the end of the list.',
 'extend': 'method of a list to add multiple items to the end of the list.',
 'insert': 'method of a list to insert an item at a specific position.',
 'timer': '(Not a built-in function) refers to a way to measure the time taken by a section of code to execute.',
 'globals': 'built-in dictionary containing global variables.',
 'copy': 'module to create shallow or deep copies of objects.',
 'deepcopy': 'function in the copy module to create a deep copy of an object.',
 'upper': 'method of string to convert all characters to uppercase.',
 'lower': 'method of string to convert all characters to lowercase.',
 'title': 'method of string to convert the first letter of each word to uppercase.',
 'casefold': 'method of string to convert string to a case-insensitive form.',
 'rstrip': 'method of string to remove whitespaces from the right end of the string.',
 'for_loop': 'type of loop that iterates over a collection and executes a block of code for each iteration.',
 'enumerate': 'function to iterate over a sequence and get index and value for each item.',
 'sum': 'built-in function to add items of an iterable and return the sum.',
 'mean': 'the average of a set of numbers',
 'fmean': 'a numpy function that computes the arithmetic mean of input elements, ignoring NaN values',
 'fillna': 'a pandas method that fills missing values with a specified value or method',
 'pandas': 'an open-source library for data analysis and manipulation in Python',
 'dict': 'short for dictionary, a built-in Python data type that stores key-value pairs',
 'hash': 'a function that converts an input value into a fixed-size output value (hash code)',
 '.DataFrame()': 'a pandas constructor that creates a dataframe from various inputs',
 '.clear()': 'a dictionary method that removes all items from the dictionary',
 'keys': 'a dictionary view that displays a list of all keys in a dictionary',
 'fromkeys': 'a built-in dictionary method that creates a new dictionary with specified keys and values',
 '.get()': 'a dictionary method that retrieves the value of a specified key and returns None if the key is not found',
 '.update()': 'a dictionary method that updates the dictionary with the key-value pairs from another dictionary or from an iterable object',
 'set': 'a built-in Python data type that stores an unordered collection of unique elements',
 '.isdisjoint()': 'a set method that returns True if two sets have no elements in common, and False otherwise',
 '.add()': 'a set method that adds an element to the set',
 '.remove()': 'a set method that removes a specified element from the set.',
 'discard()': 'Removes an element from a set, if it is present',
 '&': 'Bitwise AND operation between two sets, returns elements present in both sets',
 '|': 'Bitwise OR operation between two sets, returns elements present in either set',
 '**': 'Exponentiation operator, raises the first operand to the power of the second',
 '*': 'Multiplication operator, returns the product of two operands',
 '=': 'Assignment operator, assigns the value of the second operand to the first',
 '==': 'Equality operator, returns True if both operands are equal, else False',
 'String Library': 'A collection of string-related functions in Python',
 '.ascii_upper': 'A string of the uppercase letters "A" through "Z", ASCII codes 65 to 90',
 '.ascii_lower': 'A string of the lowercase letters "a" through "z", ASCII codes 97 to 122',
 '.ascii_letters': 'A string of all the ASCII letters "a" through "z" and "A" through "Z"',
 'sqrt()': 'A function that returns the square root of a number',
 'perf_counter()': 'A function that returns the value (in seconds) of a performance counter, a monotonically increasing timer',
 '.split()': 'A string method that returns a list of strings by splitting a string into substrings based on a specified separator',
 '.items()': 'A method that returns a view of the dictionarys items as key-value pairs',
 '.value': 'An attribute or method that retrieves the value associated with a key in a dictionary',
 '.replace()': 'A string method that returns a copy of the string with specified replacements made',
 'Counter()': 'A built-in Python collection that counts the number of occurrences of elements in a list or other iterable'}

In [11]:
df_pymethods.drop('description', axis=1, inplace=True)

In [12]:
df_pymethods

             0
0       format
1          abs
2        float
3        range
4      __add__
..         ...
63    .split()
64    .items()
65      .value
66  .replace()
67   Counter()

[68 rows x 1 columns]

In [13]:
df_pymethods['description'] = pd.Series(method_desc)

In [14]:
df_pymethods.drop('description', axis=1, inplace=True)

In [15]:
df_pymethods

             0
0       format
1          abs
2        float
3        range
4      __add__
..         ...
63    .split()
64    .items()
65      .value
66  .replace()
67   Counter()

[68 rows x 1 columns]

In [16]:
df_method_desc = pd.Series(method_desc)

In [17]:
df_method_desc

format        function to format strings, used to replace pl...
abs                 function to get absolute value of a number.
float         built-in data type to represent a floating-poi...
range         function to generate a sequence of numbers, ty...
add           magic method to overload the '+' operator, typ...
                                    ...
.split()      A string method that returns a list of strings...
.items()      A method that returns a view of the dictionary...
.value        An attribute or method that retrieves the valu...
.replace()    A string method that returns a copy of the str...
Counter()     A built-in Python collection that counts the n...
Length: 67, dtype: object

In [18]:
df_pymethods['description'] = df_method_desc

In [19]:
df_pymethods.drop('description', axis=1, inplace=True)

In [20]:
print(df_pymethods)
print(df_method_desc)

             0
0       format
1          abs
2        float
3        range
4      __add__
..         ...
63    .split()
64    .items()
65      .value
66  .replace()
67   Counter()

[68 rows x 1 columns]
format        function to format strings, used to replace pl...
abs                 function to get absolute value of a number.
float         built-in data type to represent a floating-poi...
range         function to generate a sequence of numbers, ty...
add           magic method to overload the '+' operator, typ...
                                    ...
.split()      A string method that returns a list of strings...
.items()      A method that returns a view of the dictionary...
.value        An attribute or method that retrieves the valu...
.replace()    A string method that returns a copy of the str...
Counter()     A built-in Python collection that counts the n...
Length: 67, dtype: object

In [21]:
pd.read_excel(r"C:\Users\light\OneDrive\Desktop\df_pymethods.xlsx")

              name                                               desc
0                &  Bitwise AND operation between two sets, return...
1                *  Multiplication operator, returns the product o...
2               **  Exponentiation operator, raises the first oper...
3           .add()       a set method that adds an element to the set
4   .ascii_letters  A string of all the ASCII letters "a" through ...
..             ...                                                ...
72      new method                             new method description
73      new method                             new method description
74      new method                             new method description
75      new method                             new method description
76      new method                             new method description

[77 rows x 2 columns]

In [22]:
df_python_methods = pd.read_excel(r"C:\Users\light\OneDrive\Desktop\df_pymethods.xlsx")

In [23]:
df_python_methods.head(20)

              name                                               desc
0                &  Bitwise AND operation between two sets, return...
1                *  Multiplication operator, returns the product o...
2               **  Exponentiation operator, raises the first oper...
3           .add()       a set method that adds an element to the set
4   .ascii_letters  A string of all the ASCII letters "a" through ...
5     .ascii_lower  A string of the lowercase letters "a" through ...
6     .ascii_upper  A string of the uppercase letters "A" through ...
7         .clear()  a dictionary method that removes all items fro...
8     .DataFrame()  a pandas constructor that creates a dataframe ...
9           .get()  a dictionary method that retrieves the value o...
10   .isdisjoint()  a set method that returns True if two sets hav...
11        .items()  A method that returns a view of the dictionary...
12       .remove()  a set method that removes a specified element ...
13      .replace()  A string method that returns a copy of the str...
14        .split()  A string method that returns a list of strings...
15       .update()  a dictionary method that updates the dictionar...
16          .value  An attribute or method that retrieves the valu...
17               |  Bitwise OR operation between two sets, returns...
18               =  Assignment operator, assigns the value of the ...
19              ==  Equality operator, returns True if both operan...

In [24]:
df_python_methods.columns = ['name', 'desc']

In [25]:
df_python_methods

              name                                               desc
0                &  Bitwise AND operation between two sets, return...
1                *  Multiplication operator, returns the product o...
2               **  Exponentiation operator, raises the first oper...
3           .add()       a set method that adds an element to the set
4   .ascii_letters  A string of all the ASCII letters "a" through ...
..             ...                                                ...
72      new method                             new method description
73      new method                             new method description
74      new method                             new method description
75      new method                             new method description
76      new method                             new method description

[77 rows x 2 columns]

In [26]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [27]:
df_method_desc['float']

'built-in data type to represent a floating-point number.'

In [28]:
df_python_methods[0:30]

                name                                               desc
0                  &  Bitwise AND operation between two sets, return...
1                  *  Multiplication operator, returns the product o...
2                 **  Exponentiation operator, raises the first oper...
3             .add()       a set method that adds an element to the set
4     .ascii_letters  A string of all the ASCII letters "a" through ...
5       .ascii_lower  A string of the lowercase letters "a" through ...
6       .ascii_upper  A string of the uppercase letters "A" through ...
7           .clear()  a dictionary method that removes all items fro...
8       .DataFrame()  a pandas constructor that creates a dataframe ...
9             .get()  a dictionary method that retrieves the value o...
10     .isdisjoint()  a set method that returns True if two sets hav...
11          .items()  A method that returns a view of the dictionary...
12         .remove()  a set method that removes a specified element ...
13        .replace()  A string method that returns a copy of the str...
14          .split()  A string method that returns a list of strings...
15         .update()  a dictionary method that updates the dictionar...
16            .value  An attribute or method that retrieves the valu...
17                 |  Bitwise OR operation between two sets, returns...
18                 =  Assignment operator, assigns the value of the ...
19                ==  Equality operator, returns True if both operan...
20               abs        function to get absolute value of a number.
21               add  magic method to overload the '+' operator, typ...
22            append  method of a list to add an item to the end of ...
23  as_integer_ratio  method of float to get a numerator and denomin...
24          casefold  method of string to convert string to a case-i...
25              copy  module to create shallow or deep copies of obj...
26         Counter()  A built-in Python collection that counts the n...
27          deepcopy  function in the copy module to create a deep c...
28               del  statement to delete an object, such as an item...
29              dict  short for dictionary, a built-in Python data t...

In [29]:
df_python_methods

,name,desc
0,&,"Bitwise AND operation between two sets, return..."
1,*,"Multiplication operator, returns the product o..."
2,**,"Exponentiation operator, raises the first oper..."
3,.add(),a set method that adds an element to the set
4,.ascii_letters,"A string of all the ASCII letters ""a"" through ..."
5,.ascii_lower,"A string of the lowercase letters ""a"" through ..."
6,.ascii_upper,"A string of the uppercase letters ""A"" through ..."
7,.clear(),a dictionary method that removes all items fro...
8,.DataFrame(),a pandas constructor that creates a dataframe ...
9,.get(),a dictionary method that retrieves the value o...
10,.isdisjoint(),a set method that returns True if two sets hav...
11,.items(),A method that returns a view of the dictionary...
12,.remove(),a set method that removes a specified element ...
13,.replace(),A string method that returns a copy of the str...
14,.split(),A string method that returns a list of strings...
15,.update(),a dictionary method that updates the dictionar...
16,.value,An attribute or method that retrieves the valu...
17,|,"Bitwise OR operation between two sets, returns..."
18,=,"Assignment operator, assigns the value of the ..."
19,==,"Equality operator, returns True if both operan..."
20,abs,function to get absolute value of a number.
21,add,"magic method to overload the '+' operator, typ..."
22,append,method of a list to add an item to the end of ...
23,as_integer_ratio,method of float to get a numerator and denomin...
24,casefold,method of string to convert string to a case-i...
25,copy,module to create shallow or deep copies of obj...
26,Counter(),A built-in Python collection that counts the n...
27,deepcopy,function in the copy module to create a deep c...
28,del,"statement to delete an object, such as an item..."
29,dict,"short for dictionary, a built-in Python data t..."
30,discard(),"Removes an element from a set, if it is present"
31,elif,(else if) keyword used in a conditional statem...
32,enumerate,function to iterate over a sequence and get in...
33,extend,method of a list to add multiple items to the ...
34,fillna,a pandas method that fills missing values with...
35,float,built-in data type to represent a floating-poi...
36,fmean,a numpy function that computes the arithmetic ...
37,for_loop,type of loop that iterates over a collection a...
38,format,"function to format strings, used to replace pl..."
39,fromkeys,a built-in dictionary method that creates a ne...
40,globals,built-in dictionary containing global variables.
41,hash,a function that converts an input value into a...
42,id,function to get the identity of an object in m...
43,if_else,"(Not a built-in function, but rather a concept..."
44,init,"magic method for initializing an object, calle..."
45,insert,method of a list to insert an item at a specif...
46,keys,a dictionary view that displays a list of all ...
47,len,built-in function to get the length of an obje...
48,list,built-in data type to store ordered collection...
49,lower,method of string to convert all characters to ...
50,mean,the average of a set of numbers
51,ord,function to get the unicode code point of a si...
52,pandas,an open-source library for data analysis and m...
53,perf_counter(),A function that returns the value (in seconds)...
54,range,"function to generate a sequence of numbers, ty..."
55,rstrip,method of string to remove whitespaces from th...
56,set,a built-in Python data type that stores an uno...
57,slice,"object to extract a portion of a sequence, suc..."
58,sqrt(),A function that returns the square root of a n...
59,str,built-in function to convert any object to a s...
60,String Library,A collection of string-related functions in Py...
61,sum,built-in function to add items of an iterable ...
62,ternary conditional operator,shorthand syntax to write an if-else statement...
63,timer,(Not a built-in function) refers to a way to m...
64,title,method of string to convert the first letter o...
65,tuple,built-in data type to store ordered collection...
66,upper,method of string to convert all characters to ...
67,raise ValueError(),exception object ('custom message')
68,new method,new method description
69,new method,new method description
70,new method,new method description
71,new method,new method description
72,new method,new method description
73,new method,new method description
74,new method,new method description
75,new method,new method description
76,new method,new method description

In [30]:
pd.set_option('display.max_colwidth', 1000)

In [31]:
df_python_methods_test = pd.read_excel(r"C:\Users\light\OneDrive\Desktop\df_pymethods.xlsx")

In [32]:
df_pymethods = df_python_methods_test